### ISSUE TITLE
删除数据库中无用的字段

### ISSUE THREAD

**Issue by DoraemonXX** [biggeng/OCSP#2]
- STREAM_LABEL表的cache_id字段

- STREAM_TASK表中的tid删除，代码中需要将原有引用tid的地方修改为引用id；将tname修改为name，并修改相应的代码

- 删除STREAM_SYSTEMPROP表中如下属性：
 + batchSize
 + queue
 + interface_class
 + subject_class
 + codisQryThreadNum
 + pipeLineBatch

**Comment by DoraemonXX** [comment]
@biggeng please review the changes, thanks.

此问题需要删除的字段中，只有tid，tname，queue涉及到修改代码

- 删除tid，tname涉及到的文件TaskConf.scala，StreamTaskFactory.scala，TaskServer.scala

- 删除queue涉及到的文件MainFrameManager.scala
 + 修改方案：如果获取不到queue，或者获取到的queue为空，那么提交spark任务的时候不指定--queue，这样yarn会自动将任务调度到默认的队列
 

**Attachments**
[Issue-2.diff.txt](https://github.com/biggeng/OCSP/files/518971/issue2.diff.txt)

**Comment by biggeng** [comment]
Thanks @DoraemonXX . The diff is OK to me. Please go ahead.

**Comment by DoraemonXX** [comment]
Fixed
