### ISSUE TITLE
将jedis的相关配置整合

### ISSUE THREAD

**Issue by DoraemonXX** [biggeng/OCSP#3]
- 删除如下配置

  jedisPoolMaxTotal
  jedisPoolMaxIdle
jedisPoolMinIdle
jedisPoolMEM
JedisMaxTotal
JedisMaxIdle
JedisMEM
- 增加新的配置

 jedisMaxTotal
jedisMaxIdle
jedisMinIdle
jedisMEM
- 在代码中用新的配置项替换原有删除的配置

**Comment by DoraemonXX** [comment]
@biggeng please review the changes, thanks.

- CodisCacheManager.scala

- JodisCacheManager.scala

**Attachments**
[Issue-3.txt](https://github.com/biggeng/OCSP/files/518666/issue3.diff.txt)

**Comment by biggeng** [comment]
Thanks! @DoraemonXX . The diff is ok to me. Please go ahead.

**Comment by DoraemonXX** [comment]
Fixed
