### ISSUE TITLE
CodisProxy与cacheServers合并

### ISSUE THREAD

**Issue by DoraemonXX** [biggeng/OCSP#4]
排查代码中CodisProxy与cacheServers使用场景，并将无用的删除

**Comment by DoraemonXX** [comment]
@biggeng 

- 通过排查代码，CodisProxy参数并没有使用，所以可以删除

- cacheServers是在CodisCacheManager中使用，多个address用逗号分隔

综上，此issue不需要修改代码，只要在数据库中清除CodisProxy即可

**Comment by biggeng** [comment]
Thanks. Close this issue since it has been fixed.
