### ISSUE TITLE
优化数据库中codis的相关配置

### ISSUE THREAD

**Issue by DoraemonXX** [biggeng/OCSP#5]
将STREAM_SYSTEMPROP表中的如下字段，移到STREAM_DATASOURCE表中的type为codis的属性里面

- cacheServers

- jedisMaxIdle

- jedisMaxTotal

- jedisMEM

- jedisMinIdle

- zk

- zkSessionTimeoutMs

- zkpath

- jedisTimeOut

**Comment by DoraemonXX** [comment]
@biggeng please review the changes, thanks.

- 涉及要修改的文件：CodisCacheManager.scala，JodisCacheManager.scala，MainFrameConf.scala

- 修改方案：在MainFrameConf初始化的时候根据STREAM_DATASOURCE表中的type字段获取codis的所有相关属性，这样CodisCacheManager与JodisCacheManager每次使用的时候不需要再连接数据库查询；另外删除了MainFrameConf中多余的注释掉的代码。

**Attachments**
[Issue-5.txt](https://github.com/biggeng/OCSP/files/519407/issue5.diff.txt)

**Comment by biggeng** [comment]
Thanks. Please go ahead. @DoraemonXX

**Comment by DoraemonXX** [comment]
Fixed
